-- Migración 062: Sincronización de tabla page_images (Parte 13)
-- Generada: 2026-05-14 13:25:20

SET NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';
SET FOREIGN_KEY_CHECKS = 0;
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('609', '298', 'assets/images/p298/img_69fd075c3daef_Morata10.jpg', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('610', '298', 'assets/images/p298/img_69fd075c3eb99_Morata20.jpg', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('611', '298', 'assets/images/p298/img_69fd075c42730_pueblo20.jpg', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('612', '298', 'assets/images/p298/img_69fd075c44c0b_pueblo50.jpg', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('613', '298', 'assets/images/p298/img_69fd075c46b7b_pueblo70.jpg', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('614', '300', 'assets/images/p300/img_69fd075c4ee21_lamp_eme.gif', NULL, '1');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('615', '300', 'assets/images/p300/img_69fd075c4febf_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('616', '300', 'assets/images/p300/img_69fd075c5084a_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('617', '300', 'assets/images/p300/img_69fd075c51150_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('618', '300', 'assets/images/p300/img_69fd075c518ef_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('619', '300', 'assets/images/p300/img_69fd075c520f8_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('620', '300', 'assets/images/p300/img_69fd075c52993_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('621', '300', 'assets/images/p300/img_69fd075c535a2_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('622', '300', 'assets/images/p300/img_69fd075c53e46_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('623', '300', 'assets/images/p300/img_69fd075c54972_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('624', '300', 'assets/images/p300/img_69fd075c55124_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('625', '300', 'assets/images/p300/img_69fd075c55832_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('626', '300', 'assets/images/p300/img_69fd075c55f32_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('627', '300', 'assets/images/p300/img_69fd075c56707_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('628', '300', 'assets/images/p300/img_69fd075c56eeb_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('629', '300', 'assets/images/p300/img_69fd075c577f6_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('630', '300', 'assets/images/p300/img_69fd075c5846a_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('631', '300', 'assets/images/p300/img_69fd075c58d24_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('632', '300', 'assets/images/p300/img_69fd075c594db_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('633', '300', 'assets/images/p300/img_69fd075c59ca9_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('634', '300', 'assets/images/p300/img_69fd075c5a524_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('635', '300', 'assets/images/p300/img_69fd075c5ae19_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('636', '300', 'assets/images/p300/img_69fd075c5b916_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('637', '300', 'assets/images/p300/img_69fd075c5c349_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('638', '300', 'assets/images/p300/img_69fd075c5cd1c_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('639', '300', 'assets/images/p300/img_69fd075c5d6a4_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('640', '300', 'assets/images/p300/img_69fd075c5de26_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('641', '300', 'assets/images/p300/img_69fd075c5e7bb_lamp_eme.gif', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('642', '305', 'uploads/artesania/ana-maria/Panuelos_y_corbatas.jpg', 'Pa??uelos y corbatas en seda', '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('643', '305', 'uploads/artesania/ana-maria/Desnudo-1.jpg', 'Desnudo - Seda', '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('644', '305', 'uploads/artesania/ana-maria/Mariposa.jpg', 'Mariposa - Seda', '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('645', '305', 'uploads/artesania/ana-maria/Suenos.jpg', 'Sue??os - Seda', '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('646', '305', 'uploads/artesania/ana-maria/Santa_Ana.jpg', 'Pintura mural - Ermita de Santa Ana', '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('647', '305', 'uploads/artesania/ana-maria/Estandarte.jpg', 'Estandarte procesional', '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('648', '305', 'uploads/artesania/ana-maria/Granadas-1.jpg', 'Granadas - Pintura al pastel', '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('829', '392', 'uploads/asociaciones/asoc_automovilismo_2005_0.jpg', NULL, '1');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('830', '392', 'uploads/asociaciones/asoc_automovilismo_2005_1.jpg', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('831', '393', 'uploads/asociaciones/asoc_automovilismo_2006_0.jpg', NULL, '1');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('832', '393', 'uploads/asociaciones/asoc_automovilismo_2006_1.jpg', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('833', '393', 'uploads/asociaciones/asoc_automovilismo_2006_2.jpg', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('834', '393', 'uploads/asociaciones/asoc_automovilismo_2006_3.jpg', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('835', '395', 'uploads/asociaciones/asoc_baloncesto_2005_0.jpg', NULL, '1');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('836', '395', 'uploads/asociaciones/asoc_baloncesto_2005_1.jpg', NULL, '0');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('837', '396', 'uploads/asociaciones/asoc_baloncesto_2006_0.jpg', NULL, '1');
REPLACE INTO `page_images` (`id`, `page_id`, `image_path`, `caption`, `is_cover`) VALUES ('838', '396', 'uploads/asociaciones/asoc_baloncesto_2006_1.jpg', NULL, '0');

SET FOREIGN_KEY_CHECKS = 1;
