CREATE TABLE IF NOT EXISTS `quotes` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `phrase` TEXT NOT NULL,
    `author` VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
