-- Migración 082: Datos iniciales de bares y restaurantes de Moratalla
-- Fuente: https://moratalla.es/soy-turista/donde-comer/
-- Fecha: 2026-06-18

INSERT INTO `restaurantes`
    (`nombre`, `calle`, `poblacion`, `es_pedania`, `municipio`, `provincia`, `codigo_postal`, `telefono1`, `telefono2`, `web`, `facebook`, `tripadvisor`, `gmap_url`, `is_visible`, `sort_order`)
VALUES
('Restaurante Alhárabe – Camping La Puerta', 'Camping La Puerta, km 8', 'La Puerta', 1, 'Moratalla', 'Murcia', '30440', '968730008', NULL, 'https://www.campinglapuerta.com/restaurante.html', NULL, NULL, 'https://www.google.com/maps/search/?api=1&query=Restaurante+Alharabe+Camping+La+Puerta+Moratalla+Murcia', 1, 10),
('Restaurante El Cortijo', 'Ctra. De Nerpio – Campo de San Juan', 'Campo de San Juan', 1, 'Moratalla', 'Murcia', '30441', '678770082', NULL, NULL, 'https://www.facebook.com/Restaurante-El-cortijo-campo-de-san-juan-103949274526103/', NULL, 'https://www.google.com/maps/search/?api=1&query=Restaurante+El+Cortijo+Campo+San+Juan+Moratalla+Murcia', 1, 20),
('Restaurante Casa Pernías', 'MU-702, km 23', 'Moratalla', 0, 'Moratalla', 'Murcia', '30441', '968726311', NULL, 'https://casapernias.com/', NULL, NULL, 'https://www.google.com/maps/search/?api=1&query=Restaurante+Casa+Pernias+Moratalla+Murcia', 1, 30),
('Bar Restaurante La Terraza', 'C/ Iglesia, 5', 'El Sabinar', 1, 'Moratalla', 'Murcia', '30440', '968738052', NULL, NULL, NULL, NULL, 'https://www.google.com/maps/search/?api=1&query=Bar+Restaurante+La+Terraza+El+Sabinar+Moratalla', 1, 40),
('Bar El Jardín', 'Plaza de la Ventas, 1', 'El Sabinar', 1, 'Moratalla', 'Murcia', '30440', '649050127', NULL, NULL, 'https://www.facebook.com/p/Bar-jard%C3%ADnSabinar-100064168687697/', NULL, 'https://www.google.com/maps/search/?api=1&query=Bar+El+Jardin+El+Sabinar+Moratalla+Murcia', 1, 50),
('Bar-Restaurante Piñero', 'Callejón Escalera', 'Benizar', 1, 'Moratalla', 'Murcia', '30442', '616369258', NULL, NULL, 'https://www.facebook.com/PineroBenizar', NULL, 'https://www.google.com/maps/search/?api=1&query=Bar+Restaurante+Pinero+Benizar+Moratalla+Murcia', 1, 60),
('Terraza Revolcadores', 'Calle Cementerio', 'Cañada de la Cruz', 1, 'Moratalla', 'Murcia', '30414', '660797539', NULL, NULL, 'https://www.facebook.com/terrazarevolcadores/?locale=es_ES', NULL, 'https://www.google.com/maps/search/?api=1&query=Terraza+Revolcadores+Canada+de+la+Cruz+Moratalla+Murcia', 1, 70),
('Restaurante El Nogal', 'Inazares', 'Inazares', 1, 'Moratalla', 'Murcia', '30413', '968736379', NULL, NULL, 'https://www.facebook.com/elnogal.inazares/', NULL, 'https://www.google.com/maps/search/?api=1&query=Restaurante+El+Nogal+Inazares+Moratalla+Murcia', 1, 80),
('Bar Alhárabe', 'Ctra. Campo de San Juan', 'Alhárabe', 1, 'Moratalla', 'Murcia', '30440', '680461024', NULL, NULL, NULL, NULL, 'https://www.google.com/maps/search/?api=1&query=Bar+Alharabe+Moratalla+Murcia', 1, 90),
('Bar Los Cazadores', 'Ctra. Calasparra, 40', 'Moratalla', 0, 'Moratalla', 'Murcia', '30440', '641197477', NULL, NULL, NULL, NULL, 'https://www.google.com/maps/search/?api=1&query=Bar+Los+Cazadores+Moratalla+Murcia', 1, 100),
('Mesón La Farola', 'C. Mayor, 66', 'Moratalla', 0, 'Moratalla', 'Murcia', '30440', '617887817', NULL, NULL, NULL, NULL, 'https://maps.app.goo.gl/GFazWRtUHKYdq19r7', 1, 110),
('Retiro Gastro – Rural', 'Ctra. La Puerta, km 2', 'Moratalla', 0, 'Moratalla', 'Murcia', '30440', '619109424', NULL, NULL, NULL, NULL, 'https://maps.app.goo.gl/6e7WFg2gYnt3jRvz5', 1, 120),
('Bombay Kebab', 'Ctra. San Juan, 6', 'Moratalla', 0, 'Moratalla', 'Murcia', '30440', '968706147', NULL, NULL, NULL, NULL, 'https://maps.app.goo.gl/cS6orUJfMEWDwFVs8', 1, 130),
('Bar – Salón Social – Calar de la Santa', 'Calar de la Santa', 'Calar de la Santa', 1, 'Moratalla', 'Murcia', '30440', '649418873', NULL, NULL, NULL, NULL, 'https://www.google.com/maps/search/?api=1&query=Calar+de+la+Santa+Moratalla+Murcia', 1, 140),
('Restaurante Albergue La Pava', 'Caserio La Pava, 5', 'La Pava', 1, 'Moratalla', 'Murcia', '30440', '616055547', NULL, NULL, NULL, NULL, 'https://www.google.com/maps/search/?api=1&query=Restaurante+Albergue+La+Pava+Moratalla+Murcia', 1, 150),
('Kebab House', 'Carr. Campo de San Juan, 36', 'Moratalla', 0, 'Moratalla', 'Murcia', '30440', '868665134', NULL, 'https://moratallakebabhouse.es/', NULL, NULL, 'https://www.google.com/maps/search/?api=1&query=Kebab+House+Moratalla+Murcia', 1, 160),
('Restaurante La Cilla', 'Santuario Casa de Cristo, km 7', 'Moratalla', 0, 'Moratalla', 'Murcia', '30440', '601854121', NULL, 'https://lacillamoratalla.es/', NULL, NULL, 'https://www.google.com/maps/search/?api=1&query=Restaurante+La+Cilla+Moratalla+Murcia', 1, 170),
('Taberna Tau Chen', 'C. B, 13', 'La Tercia', 1, 'Moratalla', 'Murcia', '30442', '679052712', NULL, NULL, NULL, 'https://www.tripadvisor.com/Restaurant_Review-g1047904-d15543112-Reviews-Taberna_Tau_Chen-Moratalla.html', 'https://www.google.com/maps/search/?api=1&query=Taberna+Tau+Chen+La+Tercia+Moratalla+Murcia', 1, 180),
('Restaurante El Sitio', 'Ctra. Caravaca, 26', 'Moratalla', 0, 'Moratalla', 'Murcia', '30440', '608621680', NULL, 'https://elsitiodemoratalla.es', NULL, NULL, 'https://www.google.com/maps/search/?api=1&query=Restaurante+El+Sitio+Moratalla+Murcia', 1, 190),
('Restaurante Pizzería Il Pipiolo', 'Ctra. Campo de San Juan, 73', 'Moratalla', 0, 'Moratalla', 'Murcia', '30440', '968730228', NULL, 'https://pipiolopizzerias.com', NULL, NULL, 'https://www.google.com/maps/search/?api=1&query=Pizzeria+Il+Pipiolo+Moratalla+Murcia', 1, 200),
('Taberna Moncloa', 'Ctra. Campo de San Juan, 34', 'Moratalla', 0, 'Moratalla', 'Murcia', '30440', '968706233', '660392104', NULL, 'https://www.facebook.com/tabernamoncloa/', NULL, 'https://www.google.com/maps/search/?api=1&query=Taberna+Moncloa+Moratalla+Murcia', 1, 210),
('Restaurante Montebenamor', 'Carr. Campo de San Juan, 67', 'Moratalla', 0, 'Moratalla', 'Murcia', '30440', '630121087', NULL, NULL, 'https://m.facebook.com/Restaurante-Montebenamor-1125264384159505/', NULL, 'https://www.google.com/maps/search/?api=1&query=Restaurante+Montebenamor+Moratalla+Murcia', 1, 220),
('Restaurante Alanshé', 'C/ Tomás Aguilera (frente Jardín La Glorieta)', 'Moratalla', 0, 'Moratalla', 'Murcia', '30440', '689797819', '618917988', NULL, 'https://www.facebook.com/p/Alansh%C3%A9-Bar-Taperia-61555311501496/', NULL, 'https://www.google.com/maps/search/?api=1&query=Restaurante+Alanshe+Moratalla+Murcia', 1, 230),
('Palike', 'C/ Lucas Egea, 2', 'Moratalla', 0, 'Moratalla', 'Murcia', '30440', '653795674', NULL, NULL, 'https://www.facebook.com/palikemoratalla/', NULL, 'https://www.google.com/maps/search/?api=1&query=Palike+Moratalla+Murcia', 1, 240),
('Brasería Casa Manolo', 'Carretera de Caravaca, 62', 'Moratalla', 0, 'Moratalla', 'Murcia', '30440', '685739868', NULL, NULL, 'https://www.facebook.com/p/Braser%C3%ADa-Casa-Manolo-100063577151356/', NULL, 'https://www.google.com/maps/search/?api=1&query=Braseria+Casa+Manolo+Moratalla+Murcia', 1, 250),
('Tasca El Coto', 'Ctra. de Caravaca, 20', 'Moratalla', 0, 'Moratalla', 'Murcia', '30440', '670455543', NULL, NULL, NULL, 'https://www.tripadvisor.es/Restaurant_Review-g1047904-d10161547-Reviews-Tasca_El_Coto-Moratalla.html', 'https://www.google.com/maps/search/?api=1&query=Tasca+El+Coto+Moratalla+Murcia', 1, 260),
('Café Bar Reyes', 'C. Don Tomás el Cura, 7', 'Moratalla', 0, 'Moratalla', 'Murcia', '30440', '691071598', NULL, NULL, NULL, NULL, 'https://www.google.com/maps/search/?api=1&query=Bar+Reyes+Moratalla', 1, 270),
('Bar El Agarre', 'Ctra. del Canal, 8', 'Moratalla', 0, 'Moratalla', 'Murcia', '30440', '650535399', NULL, NULL, NULL, NULL, 'https://www.google.com/maps/search/?api=1&query=Bar+El+Agarre+Moratalla', 1, 280),
('Bar Carlos Sixto', 'Pl. de Tamayo, 2', 'Moratalla', 0, 'Moratalla', 'Murcia', '30440', '652982567', NULL, NULL, 'https://www.facebook.com/barcarlossixto/', NULL, 'https://www.google.com/maps/search/?api=1&query=Bar+Carlos+Sixto+Moratalla+Murcia', 1, 290);
