ALTER TABLE `pages` MODIFY COLUMN `icon` VARCHAR(255) NULL DEFAULT 'far fa-file-alt';
ALTER TABLE `news_events` MODIFY COLUMN `icon` VARCHAR(255) NULL DEFAULT '📰';
ALTER TABLE `categories` MODIFY COLUMN `icon` VARCHAR(255) NULL DEFAULT '📁';
ALTER TABLE `external_links` MODIFY COLUMN `icon` VARCHAR(255) NULL DEFAULT '🔗';
